---
apiVersion: v1
kind: Service
metadata:
  name: capstone-service
spec:
  type: NodePort
  selector:
    app: capstoneapp
  ports:
  - protocol: TCP
    port: 8079
    targetPort: 8079
    nodePort: 32001
